###

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "Akshitha",
  "email": "akshitha@gmail.com",
  "password": "123456"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "akshitha@gmail.com",
  "password": "123456"
}


//movies
###

POST http://localhost:5000/api/movies/add
Content-Type: application/json

{
    "title": "K3G",
    "genre": "Romance Drama",
    "description": "A young man and woman discover love and self-realization during a memorable boat journey on the Godavari River.",
    "poster": "https://upload.wikimedia.org/wikipedia/en/8/8b/Godavari_film_poster.jpg",
    "rating": 8.2,
    "year": 2006

}


###

GET http://localhost:5000/api/movies
Content-Type: application/json

{
    "_id": "...",
    "title": "Interstellar",
    "genre": "Sci-Fi"
}


###
GET http://localhost:5000/api/movies/6a1efc4f55e077ff53e44e63