###

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "Akshitha",
  "email": "akshitha@gmail.com",
  "password": "123456"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "akshitha@gmail.com",
  "password": "123456"
}


//movies
###

POST http://localhost:5000/api/movies/add
Content-Type: application/json

{
  "title": "Hanu-Man",
  "genre": "Action / Superhero / Fantasy",
  "description": "An imaginary place called Anjanadri where a petty thief gets the powers of Lord Hanuman and fights for his village against a greedy evil force.",
  "poster": "https://i.pinimg.com/736x/aa/92/13/aa92130b5dcbb96bd933c40ae7d798e2.jpg",
  "rating": 7.9,
  "year": 2024
}


###

GET http://localhost:5000/api/movies
Content-Type: application/json

{
    "_id": "...",
    "title": "Interstellar",
    "genre": "Sci-Fi"
}
